### ISSUE TITLE
（请问有没有 plamsa applet 的开发计划

### ISSUE THREAD

**Issue by Hibanaw** [SeptemberHX/dde-mpris2-plugin#1]
在 deepin 论坛看到这个插件，十分喜欢，可惜我主力机系统是装着 kde 的 archlinux
在 kde store 看了一圈竟然没有类似的插件
kde plasma 的小组建是基于 qml 的，好像有 mpris2 的 api，不知能否在闲暇之余移植到 kde 下
不胜感激

**Comment by SeptemberHX** [comment]
KDE 有的吧，https://store.kde.org/p/1317639 这个就是啊，multimedia 分类下我看有不少类似功能的

**Comment by Hibanaw** [comment]
> KDE 有的吧，https://store.kde.org/p/1317639 这个就是啊，multimedia 分类下我看有不少类似功能的

似乎都没有显示歌词的功能，我也不知道这个功能的英文关键词是什么😥

**Comment by SeptemberHX** [comment]
歌词显示的话，貌似确实没有这个功能。但这个功能做到 KDE 里就不太合适了，因为歌词 API 不是官方的，说不定哪天就被企鹅警告了。。。有能力的话可以自己加到已有的 KDE 插件里，接口可以直接看我代码里，理论上在 qml 里加上一个歌词更新的事件、窗口以及解析功能就可以了。
