### ISSUE TITLE
[Bug] 有些歌词在滑动的时候可能会出现抖动

### ISSUE THREAD

**Issue by zsStrike** [SeptemberHX/dde-mpris2-plugin#3]
![Record_select-area_20220315101823](https://user-images.githubusercontent.com/32895764/158293068-24f6aa41-01d4-4077-bc0e-4db315b8ee16.gif)

如上图是 Bye Bye Bye 英文歌词，Lovestoned 唱奏，在歌词 did we have to turn around and say goodbye bye bye 的时候出现了抖动，经过测试，在其他英文歌曲也会存在类似的情况

可能是定时器混乱了导致 offset 增加后又重置为 0？

**Comment by SeptemberHX** [comment]
应该是 offset 的问题

**Comment by SeptemberHX** [comment]
[libdde_mpris2.zip](https://github.com/SeptemberHX/dde-mpris2-plugin/files/8250793/libdde_mpris2.zip)

试试看，我用这首歌测试没有出现这个问题了

**Comment by zsStrike** [comment]
恩恩 修复好了
