### ISSUE TITLE
按钮被遮挡

### ISSUE THREAD

**Issue by EchoGroot** [SeptemberHX/dde-mpris2-plugin#4]
![image](https://user-images.githubusercontent.com/44628981/160766008-eee54f76-b41d-4a61-b469-9163d9ba3e87.png)

屏幕分辨率：1920*1080
任务栏大小：调整到最小
系统：

![image](https://user-images.githubusercontent.com/44628981/160766141-2cc724b6-cd05-4c1e-a3bd-b2b985c1a286.png)

**Comment by SeptemberHX** [comment]
[libdde_mpris2.zip](https://github.com/SeptemberHX/dde-mpris2-plugin/files/8380683/libdde_mpris2.zip)

调整了一下高度，现在不会被遮挡了。不过此时的长宽比也不是 1：1 了，按钮变成了长方形 :)

**Comment by EchoGroot** [comment]
这样挺好的，大佬给力
![image](https://user-images.githubusercontent.com/44628981/160959345-f2a79e88-b6d1-4844-ba7e-e917a159d85e.png)
